# Generated by Django 4.2.16 on 2024-10-04 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musiciens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musiciens', models.CharField(default='musiciens dispo sur yoka', max_length=200)),
                ('bio_musiciens', models.TextField(default='musci dispo sur yoka')),
                ('age_musiciens', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('image_musiciens', models.ImageField(upload_to='media/images_musiciens')),
                ('link_social1', models.URLField(default='/music')),
                ('link_social2', models.URLField(default='/music')),
                ('link_social3', models.URLField(default='/music')),
                ('link_social4', models.URLField(default='/music')),
                ('link_social5', models.URLField(default='/music')),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='musci dispo sur yoka', max_length=200)),
                ('cover_music', models.ImageField(upload_to='media/images_cover_music')),
                ('music_file', models.FileField(upload_to='media/audio_musiciens')),
                ('transcription', models.TextField(default='musci dispo sur yoka')),
                ('date_publication', models.DateTimeField(auto_now=True)),
                ('date_sortie', models.DateTimeField(auto_now_add=True)),
                ('musiciens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yoka.musiciens')),
            ],
        ),
    ]
