# Generated by Django 4.2.16 on 2024-10-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='cover_music',
            field=models.ImageField(blank=True, upload_to='media/images_cover_music'),
        ),
        migrations.AlterField(
            model_name='music',
            name='titre',
            field=models.CharField(blank=True, default='musci dispo sur yoka', max_length=200),
        ),
        migrations.AlterField(
            model_name='music',
            name='transcription',
            field=models.TextField(blank=True, default='musci dispo sur yoka'),
        ),
        migrations.AlterField(
            model_name='musiciens',
            name='image_musiciens',
            field=models.ImageField(blank=True, upload_to='media/images_musiciens'),
        ),
        migrations.AlterField(
            model_name='musiciens',
            name='link_social1',
            field=models.URLField(blank=True, default='/music'),
        ),
        migrations.AlterField(
            model_name='musiciens',
            name='link_social2',
            field=models.URLField(blank=True, default='/music'),
        ),
        migrations.AlterField(
            model_name='musiciens',
            name='link_social3',
            field=models.URLField(blank=True, default='/music'),
        ),
        migrations.AlterField(
            model_name='musiciens',
            name='link_social4',
            field=models.URLField(blank=True, default='/music'),
        ),
        migrations.AlterField(
            model_name='musiciens',
            name='link_social5',
            field=models.URLField(blank=True, default='/music'),
        ),
    ]
