# Generated by Django 4.2.16 on 2024-10-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoka', '0002_alter_music_cover_music_alter_music_titre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musiciens',
            name='link_social1',
            field=models.URLField(blank=True, default='wwww:http://127.0.0.1:8000/'),
        ),
        migrations.AlterField(
            model_name='musiciens',
            name='link_social2',
            field=models.URLField(blank=True, default='wwww:http://127.0.0.1:8000/'),
        ),
        migrations.AlterField(
            model_name='musiciens',
            name='link_social3',
            field=models.URLField(blank=True, default='wwww:http://127.0.0.1:8000/'),
        ),
        migrations.AlterField(
            model_name='musiciens',
            name='link_social4',
            field=models.URLField(blank=True, default='wwww:http://127.0.0.1:8000/'),
        ),
        migrations.AlterField(
            model_name='musiciens',
            name='link_social5',
            field=models.URLField(blank=True, default='wwww:http://127.0.0.1:8000/'),
        ),
    ]
