# Generated by Django 4.2.16 on 2024-10-04 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoka', '0006_alter_music_musiciens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musiciens',
            name='age_musiciens',
        ),
    ]
