# Generated by Django 4.2.16 on 2024-10-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoka', '0007_remove_musiciens_age_musiciens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musiciens',
            name='bio_musiciens',
            field=models.TextField(blank=True, default='musci dispo sur yoka'),
        ),
        migrations.AlterField(
            model_name='musiciens',
            name='date_of_birth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='musiciens',
            name='musiciens',
            field=models.CharField(blank=True, default='musiciens dispo sur yoka', max_length=200),
        ),
    ]
