# Generated by Django 4.2.16 on 2024-10-05 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yoka', '0008_alter_musiciens_bio_musiciens_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musicien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, default='musicien disponible sur Yoka', max_length=200)),
                ('bio', models.TextField(blank=True, default='music disponible sur Yoka')),
                ('date_de_naissance', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='media/images_musiciens/')),
                ('link_socials', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.RemoveField(
            model_name='music',
            name='cover_music',
        ),
        migrations.RemoveField(
            model_name='music',
            name='music_file',
        ),
        migrations.RemoveField(
            model_name='music',
            name='musiciens',
        ),
        migrations.AddField(
            model_name='music',
            name='cover',
            field=models.ImageField(blank=True, upload_to='media/images_cover_music/'),
        ),
        migrations.AddField(
            model_name='music',
            name='fichier_audio',
            field=models.FileField(blank=True, upload_to='media/audio_musiciens/'),
        ),
        migrations.AlterField(
            model_name='music',
            name='titre',
            field=models.CharField(blank=True, default='music disponible sur Yoka', max_length=200),
        ),
        migrations.AlterField(
            model_name='music',
            name='transcription',
            field=models.TextField(blank=True, default='music disponible sur Yoka'),
        ),
        migrations.DeleteModel(
            name='Musiciens',
        ),
        migrations.AddField(
            model_name='music',
            name='musicien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yoka.musicien'),
        ),
    ]
