# Generated by Django 4.2.16 on 2024-10-05 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yoka', '0009_musicien_remove_music_cover_music_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicien',
            name='link_socials',
        ),
        migrations.AlterField(
            model_name='music',
            name='titre',
            field=models.CharField(blank=True, default='Musique disponible sur Yoka', max_length=200),
        ),
        migrations.AlterField(
            model_name='music',
            name='transcription',
            field=models.TextField(blank=True, default='Musique disponible sur Yoka'),
        ),
        migrations.AlterField(
            model_name='musicien',
            name='bio',
            field=models.TextField(blank=True, default='Musique disponible sur Yoka'),
        ),
        migrations.AlterField(
            model_name='musicien',
            name='nom',
            field=models.CharField(blank=True, default='Musicien disponible sur Yoka', max_length=200),
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='yoka.musicien')),
            ],
        ),
    ]
