# Generated by Django 4.2.16 on 2024-10-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoka', '0012_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
