# Generated by Django 4.2.16 on 2024-10-06 20:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yoka', '0016_remove_testimonial_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='date_post',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='message',
            field=models.TextField(blank=True, default='Yoka'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(blank=True, default='Yoka', max_length=100),
        ),
    ]
